output = open("D:/output.fasta","a+")
output_1 = open("D:/output_1.fasta")
output_2 = open("D:/output_2.fasta")
seq1=output_1.read()
seq2=output_2.read()
output.write(seq1 + "\n" + seq2)
output_1.close()
output_2.close()
output.close()
